"""
Combine Kaggle datasets and enrich with trade finance structure
Creates realistic LC, Invoice, B/L, Packing List data

Usage:
    python src/data_generation/enrich_transactions.py
    
Input:
    - data/raw/globaltradesettlenet.csv (download from Kaggle)
    - data/raw/cross_border_customs.csv (download from Kaggle)
    - data/processed/sanctions_all.csv (generated by generate_sanctions_list.py)
    
Output:
    - data/processed/transactions.csv (1,000 complete trade finance records)
"""

import pandas as pd
from faker import Faker
import random
from datetime import datetime, timedelta
import os

fake = Faker()
Faker.seed(42)  # Reproducible results
random.seed(42)

def load_kaggle_data():
    """Load the downloaded Kaggle datasets"""
    try:
        df_trade = pd.read_csv('data/raw/globaltradesettlenet.csv')
        print(f"✅ Loaded {len(df_trade)} records from GlobalTradeSettleNet")
    except FileNotFoundError:
        print("⚠️  GlobalTradeSettleNet not found, creating sample data...")
        df_trade = create_sample_trade_data(1000)
    
    try:
        df_customs = pd.read_csv('data/raw/cross_border_customs.csv')
        print(f"✅ Loaded {len(df_customs)} records from Cross-Border Customs")
    except FileNotFoundError:
        print("⚠️  Customs data not found, creating sample shipment data...")
        df_customs = create_sample_customs_data(1000)
    
    return df_trade, df_customs

def create_sample_trade_data(n=1000):
    """Fallback: Create sample trade data if Kaggle file not found"""
    print("   Creating synthetic trade data...")
    data = []
    for i in range(n):
        data.append({
            'transaction_id': f"TXN{i:05d}",
            'trade_value': random.uniform(10000, 500000),
            'currency': random.choice(['USD', 'EUR', 'GBP', 'CNY', 'HKD']),
            'origin_country': fake.country(),
            'destination_country': fake.country(),
            'payment_method': random.choice(['LC', 'TT', 'DA', 'DP']),
            'fraud_flag': random.random() < 0.05  # 5% anomalies
        })
    return pd.DataFrame(data)

def create_sample_customs_data(n=1000):
    """Fallback: Create sample customs data"""
    print("   Creating synthetic customs data...")
    ports = ['Shanghai', 'Hong Kong', 'Singapore', 'Rotterdam', 'Los Angeles', 
             'Hamburg', 'Dubai', 'Busan', 'Tokyo', 'Mumbai', 'Shenzhen', 'Qingdao']
    
    commodities = ['Textiles', 'Electronics', 'Machinery', 'Chemicals', 
                   'Cotton Fabric', 'Steel Products', 'Plastic Goods', 'Furniture']
    
    data = []
    for i in range(n):
        data.append({
            'shipment_id': f"SHIP{i:05d}",
            'origin_port': random.choice(ports),
            'destination_port': random.choice(ports),
            'customs_delay_days': random.randint(0, 10),
            'commodity': random.choice(commodities)
        })
    return pd.DataFrame(data)

def generate_trade_finance_documents(df_trade, df_customs, num_records=1000):
    """Create LC, Invoice, B/L, Packing List from base transaction data"""
    
    # Load sanctions list to inject matches
    try:
        sanctions = pd.read_csv('data/processed/sanctions_all.csv')
        sanctioned_names = sanctions['name'].tolist()
        print(f"✅ Loaded {len(sanctioned_names)} sanctioned entities for matching")
    except FileNotFoundError:
        print("⚠️  Sanctions list not found. Run generate_sanctions_list.py first.")
        sanctioned_names = []
    
    documents = []
    
    # Limit to requested number of records
    df_trade = df_trade.head(num_records)
    
    for idx, row in df_trade.iterrows():
        # Generate entities (5% chance of sanctions match)
        if random.random() < 0.05 and sanctioned_names:
            buyer_name = random.choice(sanctioned_names)
        else:
            buyer_name = fake.company()
        
        seller_name = fake.company()
        
        # Base dates
        lc_issue_date = fake.date_between(start_date='-180d', end_date='today')
        lc_expiry_date = lc_issue_date + timedelta(days=random.randint(60, 120))
        latest_ship_date = lc_expiry_date - timedelta(days=random.randint(10, 30))
        
        # Amount with REALISTIC discrepancies
        lc_amount = row.get('trade_value', random.uniform(50000, 500000))
        
        # 15% of transactions have significant discrepancies (>10%)
        # 85% have normal variance (<5%)
        if random.random() < 0.15:
            # Inject significant discrepancy (11-25% difference)
            variance = random.choice([
                random.uniform(1.11, 1.25),  # Invoice 11-25% higher
                random.uniform(0.75, 0.89)   # Invoice 11-25% lower
            ])
            invoice_amount = lc_amount * variance
        else:
            # Normal business variance (0-5%)
            invoice_amount = lc_amount * random.uniform(0.98, 1.05)
        
        # Commodity
        if idx < len(df_customs):
            commodity = df_customs.iloc[idx].get('commodity', 'General Goods')
        else:
            commodity = random.choice(['Cotton Fabric', 'Electronics', 
                                      'Machinery Parts', 'Chemicals', 'Textiles'])
        
        # Port info (from customs data if available)
        if idx < len(df_customs):
            origin_port = df_customs.iloc[idx]['origin_port']
            dest_port = df_customs.iloc[idx]['destination_port']
        else:
            origin_port = fake.city()
            dest_port = fake.city()
        
        # Shipment timing (potential delay)
        actual_ship_date = latest_ship_date + timedelta(days=random.randint(-5, 15))
        
        # Document record
        doc = {
            # Transaction metadata
            'transaction_id': f"TXN2026-{idx:05d}",
            
            # Entities
            'buyer_id': f"B{idx % 200:03d}",
            'buyer_name': buyer_name,
            'buyer_country': row.get('origin_country', fake.country()),
            'seller_id': f"S{idx % 150:03d}",
            'seller_name': seller_name,
            'seller_country': row.get('destination_country', fake.country()),
            'bank_id': f"BANK{idx % 30:03d}",
            'bank_name': random.choice(['HSBC Hong Kong', 'Standard Chartered', 
                                       'Citibank', 'DBS Bank', 'Bank of China']),
            
            # Letter of Credit
            'lc_number': f"LC2026-HK-{idx:05d}",
            'lc_issue_date': lc_issue_date.strftime('%Y-%m-%d'),
            'lc_expiry_date': lc_expiry_date.strftime('%Y-%m-%d'),
            'lc_amount': round(lc_amount, 2),
            'lc_currency': row.get('currency', 'USD'),
            'commodity': commodity,
            'incoterms': random.choice(['FOB', 'CIF', 'CFR', 'EXW']),
            'latest_ship_date': latest_ship_date.strftime('%Y-%m-%d'),
            
            # Commercial Invoice
            'invoice_number': f"INV-2026-{idx:05d}",
            'invoice_amount': round(invoice_amount, 2),
            'invoice_date': (lc_issue_date + timedelta(days=random.randint(15, 40))).strftime('%Y-%m-%d'),
            
            # Bill of Lading
            'bl_number': f"BL-{origin_port[:3].upper()}-2026-{idx:05d}",
            'shipment_date': actual_ship_date.strftime('%Y-%m-%d'),
            'port_of_loading': origin_port,
            'port_of_discharge': dest_port,
            'vessel_name': f"MV {fake.word().title()} {random.randint(1,99)}",
            
            # Packing List
            'packing_list_number': f"PL-2026-{idx:05d}",
            'total_packages': random.randint(50, 500),
            'gross_weight_kg': random.randint(5000, 50000),
            
            # Status flags (recalculate with actual amounts)
            'amount_discrepancy': abs(invoice_amount - lc_amount) > lc_amount * 0.1,
            'late_shipment': actual_ship_date > latest_ship_date,
            'fraud_flag': row.get('fraud_flag', random.random() < 0.03)
        }
        
        documents.append(doc)
    
    return pd.DataFrame(documents)

if __name__ == "__main__":
    print("\n" + "="*60)
    print("  TRADE FINANCE TRANSACTION ENRICHMENT")
    print("="*60 + "\n")
    
    # Create output directory
    os.makedirs('data/processed', exist_ok=True)
    
    print("🔄 Loading Kaggle datasets...")
    df_trade, df_customs = load_kaggle_data()
    
    print("\n🔄 Generating trade finance documents...")
    df_enriched = generate_trade_finance_documents(df_trade, df_customs, num_records=1000)
    
    # Save enriched data
    output_file = 'data/processed/transactions.csv'
    df_enriched.to_csv(output_file, index=False)
    
    print(f"\n✅ Generated {len(df_enriched)} complete trade finance records")
    print(f"\n📊 Data Quality Metrics:")
    print(f"   - Amount discrepancies: {df_enriched['amount_discrepancy'].sum()} ({df_enriched['amount_discrepancy'].sum()/len(df_enriched)*100:.1f}%)")
    print(f"   - Late shipments: {df_enriched['late_shipment'].sum()} ({df_enriched['late_shipment'].sum()/len(df_enriched)*100:.1f}%)")
    print(f"   - Fraud flags: {df_enriched['fraud_flag'].sum()} ({df_enriched['fraud_flag'].sum()/len(df_enriched)*100:.1f}%)")
    print(f"   - Unique buyers: {df_enriched['buyer_id'].nunique()}")
    print(f"   - Unique sellers: {df_enriched['seller_id'].nunique()}")
    print(f"   - Unique banks: {df_enriched['bank_id'].nunique()}")
    
    print(f"\n📁 Saved to: {output_file}")
    print(f"\n📋 Sample records:")
    print(df_enriched[['lc_number', 'buyer_name', 'lc_amount', 'lc_currency', 'commodity']].head(5))
    print("\n" + "="*60)
